toomanysource/atreus

make/golang.mk

Create new make commands `tests` and `style`:
- `tests` can run go unit tests in directory `app`.
- `style` can check go code style, which will be used in ci.
No issue.
Nothing.

feat: support run unit test and check style by 'make'

---

.github/workflows/golangci-lint.yml
.github/workflows/main.yml
make/golang.mk

create Codecov & Golangci-Lint with Github Action.
create `test-coverage` && update `tests` into `test` in makefile.

feat: create workflows yml & update makefile content

---

.github/PULL_REQUEST_TEMPLATE.md

update pull request template, make it more clear
No issue
Nothing

feat: provide more clear pull request template

---

.github/workflows/golangci-lint.yml

fix lint check `go/pkg` error
nope.
nope.

fix: fix lint check go/pkg error

---

.gitignore
configs/service/user/config.yaml
docker/build/Dockerfile
docker/service/docker-compose.yaml

support using docker-compose to run user service,.
No issue.
Nothing.

feat: support docker-compose run user service

---

app/message/service/configs/config.yaml
app/message/service/internal/conf/conf.pb.go
app/message/service/internal/conf/conf.proto

1. Add the message service configuration file
2. Modify the message configuration file

feat: update message configuration

---

pkg/minioX/minioX.go

1. Method structure for optimizing minioX

fix: Modifying minioX structures and methods

---

app/favorite/service/internal/data/favorite.go

1. Merge redundant methods into a single method
Nothing
Nothing

fix: Simplify code logic

---

pkg/kafkaX/reader.go
pkg/kafkaX/writer.go

1. Collections Writer and Reader

feat: Adding the kafkaX Collection Writer and Reader

---

app/comment/service/internal/data/comment.go
app/favorite/service/internal/data/favorite.go
app/message/service/cmd/wire_gen.go
app/publish/service/internal/data/publish.go

1. Modify the update method to use kafkaX

fix: Modifications to use kafkaX

---

app/comment/service/cmd/wire_gen.go
app/comment/service/internal/biz/comment.go
app/comment/service/internal/biz/comment_test.go
app/favorite/service/cmd/wire_gen.go
app/favorite/service/internal/biz/favorite.go
app/favorite/service/internal/biz/favorite_test.go
app/message/service/cmd/wire_gen.go
app/message/service/internal/biz/message.go
app/message/service/internal/biz/message_test.go
app/publish/service/cmd/wire_gen.go
app/publish/service/internal/biz/publish.go
app/publish/service/internal/biz/publish_test.go
app/relation/service/cmd/wire_gen.go
app/relation/service/internal/biz/relation.go
app/relation/service/internal/biz/relation_test.go

1. Cleaning up unused JWT configurations
2. Add test files for all service biz layers
Nothing
Nothing

feat: Add biz layer test files for all services

---

app/publish/service/internal/biz/publish.go
app/publish/service/internal/biz/publish_test.go
app/publish/service/internal/data/data.go
app/publish/service/internal/data/publish.go
app/publish/service/internal/server/http.go

1. Slicing and dicing the UploadVideo method.
2. Add parameter checks
3. Fixing Concurrent Conflict Issues
Nothing
Nothing

fix: [publish] Fix bugs and optimize code structure.

---

app/publish/service/configs/config.yaml

fix publish redis db_name same as comment service.
fix redis db_name in `app/publish/service/internal/conf/conf.yaml`

fix: fix publish redis db_name same as comment service

---

app/user/service/internal/biz/user.go
app/user/service/internal/biz/user_test.go
app/user/service/internal/data/data.go
app/user/service/internal/data/user.go
app/user/service/internal/service/user.go

1. Fix bugs caused by incorrect use of copier
2. Fix bugs with incorrect data due to redis not being updated
Nothing
Nothing

fix: [user]Fixing service bugs

---

app/publish/service/internal/biz/publish.go
app/publish/service/internal/data/data.go
app/publish/service/internal/data/publish.go
app/publish/service/internal/service/publish.go

1. Fix bugs where user_id = 0 is unrecognizable
2. Organize the data layer code for kafka configuration
Nothing
Nothing

fix: [publish]Optimize code formatting and fix bugs

---

pkg/kafkaX/reader.go
pkg/kafkaX/writer.go

feat: [kafkaX]Adding a reminder message

---

app/publish/service/internal/data/publish.go
app/publish/service/internal/server/http.go

1. Optimize Upload Service
2. Modify comments

fix: [publish]Optimal design

---

app/message/service/internal/data/message.go
app/message/service/internal/server/http.go

fix: [message]Fixing context acquisition

---

app/comment/service/internal/biz/comment.go
app/comment/service/internal/data/comment.go
app/comment/service/internal/server/http.go
app/comment/service/internal/service/comment.go

1. Fix redis get value error
2. Optimize structure replication

fix: [comment]Optimize structure replication, fix bugs

---

app/comment/service/internal/data/comment.go
app/favorite/service/internal/data/favorite.go
app/favorite/service/internal/data/publish.go
app/publish/service/internal/biz/publish.go
app/publish/service/internal/data/publish.go
app/publish/service/internal/data/user.go
app/relation/service/internal/data/relation.go

1. Solve cache hit problem, add placeholder keys
Nothing
1. Need to optimize the code

fix: Optimizing Redis Storage

---

app/user/service/internal/mock/export_test.go
app/user/service/internal/mock/userrepo.go
app/user/service/internal/mock/userrepo_test.go

As title.
No issue.
Next step: update package `data` logic in user service.
This fake repository is used to help with developing.

feat: provide fake repository for user service

---

configs/service/comment/config.yaml
configs/service/favorite/config.yaml
configs/service/message/config.yaml
configs/service/publish/config.yaml
configs/service/relation/config.yaml
configs/service/user/config.yaml
docker/service/docker-compose.yaml
make/common.mk
make/docker.mk

- create all service and depend in `docker-compose`
- create all service config for docker
- create parts of docker-compose in `makefile`
This docker-compose is success running in my local machine.
Nope.
Need to reviewer check want to need.
- **If the services is restart, kafka will broker duplicate, need delete `data` folder to correct.**

feat: create all service in docker-compose & create compose makefile

---

app/favorite/service/cmd/wire_gen.go
app/favorite/service/internal/biz/favorite.go
app/favorite/service/internal/data/data.go
app/favorite/service/internal/data/favorite.go
app/favorite/service/internal/data/publish.go
app/favorite/service/internal/server/server.go
app/favorite/service/internal/service/favorite.go

1. Separation of complex methods
2. Standardized error formatting
3. Fix bugs

fix: [favorite]Organize code and standardize error formatting

---

app/comment/service/cmd/main.go
app/comment/service/cmd/wire_gen.go
app/comment/service/internal/biz/biz.go
app/comment/service/internal/biz/comment.go
app/comment/service/internal/biz/comment_test.go
app/comment/service/internal/data/comment.go
app/comment/service/internal/data/data.go
app/comment/service/internal/data/user.go
app/comment/service/internal/server/server.go
app/comment/service/internal/service/comment.go

1. Separation of complex methods
2. Standardized error formatting
3. Fix bugs

fix: [comment]Organize code and standardize error formatting

---

app/relation/service/cmd/wire_gen.go
app/relation/service/internal/biz/relation.go
app/relation/service/internal/data/data.go
app/relation/service/internal/data/relation.go
app/relation/service/internal/data/user.go
app/relation/service/internal/server/server.go
app/relation/service/internal/service/relation.go

1. Separation of complex methods
2. Standardized error formatting
3. Fix bugs

fix: [relation]Organize code and standardize error formatting

---

app/relation/service/internal/data/relation.go

1. Repair the inability to display whether the user follows the fans or not when viewing the list of fans.
2. Fix that when viewing other users, other user's followings are shown as followed in the current UI
Refer to 
#81 
#82

fix: Fix bugs about follow functions

---

app/comment/service/internal/data/comment.go
app/message/service/internal/data/message.go

1. Fix bugs with incomplete copy
2. Fix chat timeout

fix: Fix bugs of incomplete copy and message timeout

---

app/favorite/service/internal/data/favorite.go
app/relation/service/internal/data/relation.go

1. Fix bugs that prevented Likes and Follows from happening

fix: Fix bugs that prevented Likes and Follows from happening

---

app/message/service/internal/biz/message.go
app/message/service/internal/biz/message_test.go
app/message/service/internal/data/message.go

1. Solve the problem of message sending display duplicates

fix: Solve the problem of message sending display duplicates

---

app/user/service/internal/biz/user.go
app/user/service/internal/data/user.go
app/user/service/internal/mock/userrepo.go
app/user/service/internal/mock/userrepo_test.go

as title, now create user data can get primary key `id` and query by `username` now can get three field information, `id`, `username` and `password`, which is biz layer needed.
no issue.
nothing.

fix: now query by user model can get necessary information

---

app/user/service/internal/data/user.go

1. Fix bugs that prevented comments from being turned on

fix: Fix bugs that prevented comments from being turned on
